import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split
from tqdm.auto import tqdm
from model_moe import MoE
from collections import Counter

# ---- Hyperparameters ----
ANSWER_PRETRAIN_NUM_EXPERTS = 32
ANSWER_PRETRAIN_HIDDEN_DIM  = 1024
TRUNK_HIDDEN                = 512
HEAD_HIDDEN                 = 256
LAMBDA_REG                  = 0.05
EPS                         = 1e-6

# ---- Training config ----
BATCH_SIZE = 32
EPOCHS     = 50
LR         = 1e-4
DEVICE     = torch.device(
    "mps" if torch.backends.mps.is_available()
    else "cuda" if torch.cuda.is_available()
    else "cpu"
)

# ---- Paths ----
DATA_DIR      = "data"
EMB_DIR       = os.path.join(DATA_DIR, "embeddings")
SPLIT_DIR     = os.path.join(DATA_DIR, "splits")
ROLEPLAY_DIR  = os.path.join(DATA_DIR, "roleplay")

RAW_CSV       = os.path.join(DATA_DIR, "mbti_1.csv")
ANSWERS_CSV   = os.path.join(ROLEPLAY_DIR, "answers_60_gpt4o.csv")

Q_IMP_CSV     = os.path.join(DATA_DIR, "priors/q_importance.csv")
Q_UNCERT_CSV  = os.path.join(DATA_DIR, "priors/q_reliability.csv")

# Pretrain (answer regression MoE) checkpoint
PRETRAIN_CKPT = os.path.join("checkpoints", "answer_pretrain", "best_pretrain.pth")

# Detect (final classifier) checkpoint
DETECT_CKPT_DIR  = os.path.join("checkpoints", "detect")
BEST_DETECT_PATH = os.path.join(DETECT_CKPT_DIR, "best_detect.pth")

# Embeddings generated by export_embeddings.py
POST_EMB_TM = {
    "train": (
        os.path.join(EMB_DIR, "train_post_embeddings.npy"),
        os.path.join(EMB_DIR, "train_post_index_map.npy"),
    ),
    "test": (
        os.path.join(EMB_DIR, "test_post_embeddings.npy"),
        os.path.join(EMB_DIR, "test_post_index_map.npy"),
    ),
}
QUEST_EMB = os.path.join(EMB_DIR, "question_embeddings.npy")

# ---- Question->Dimension mapping ----
def get_question2dim():
    return {
        **{f"Q{i}": d for i, d in zip(range(1, 11),  ["IE", "SN", "TF", "PJ", "TF", "IE", "PJ", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(11, 21), ["IE", "SN", "TF", "PJ", "TF", "IE", "SN", "TF", "SN", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(21, 31), ["IE", "SN", "TF", "PJ", "TF", "IE", "TF", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(31, 41), ["IE", "SN", "TF", "PJ", "PJ", "IE", "SN", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(41, 51), ["IE", "SN", "IE", "PJ", "TF", "SN", "TF", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(51, 61), ["IE", "SN", "IE", "TF", "TF", "PJ", "SN", "TF", "PJ", "TF"])},
    }

QUESTION_COLS = [f"Q{i}" for i in range(1, 61)]
dims = ["IE", "SN", "TF", "PJ"]

# ---- Utilities ----
def load_uids_txt(path):
    with open(path, "r", encoding="utf-8") as f:
        return [int(x.strip()) for x in f if x.strip()]

def ensure_uids_index(df):
    if "uids" not in df.columns:
        df["uids"] = range(len(df))
    df = df.set_index("uids", drop=False)
    return df

# ---- Model components ----
class GatedFusion(nn.Module):
    def __init__(self, dim_x, dim_s):
        super().__init__()
        self.f_post = nn.Linear(dim_x, dim_x)
        self.f_sub  = nn.Linear(dim_s, dim_x)
        self.gate   = nn.Linear(dim_x + dim_s, dim_x)

    def forward(self, x, s):
        g = torch.sigmoid(self.gate(torch.cat([x, s], 1)))
        return g * self.f_post(x) + (1.0 - g) * self.f_sub(s)

class DetectModel(nn.Module):
    def __init__(self, q_emb, dims_onehot, q_imp_arr, q_unc_arr, user_embs, idxs_by_dim):
        super().__init__()

        self.register_buffer("q_emb", torch.tensor(q_emb, dtype=torch.float32))
        self.register_buffer("dims_onehot", torch.tensor(dims_onehot, dtype=torch.float32))
        self.register_buffer("q_imp", torch.tensor(q_imp_arr, dtype=torch.float32))
        self.register_buffer("q_unc", torch.tensor(q_unc_arr, dtype=torch.float32))

        self.user_embs = user_embs
        self.idxs_by_dim = idxs_by_dim

        self.Dp = next(iter(user_embs.values())).shape[0]
        self.inp_dim = self.Dp + q_emb.shape[1] + 4

        # Answer-pretrain MoE (question-level regression)
        self.answer_pretrain = MoE(
            self.inp_dim,
            num_experts=ANSWER_PRETRAIN_NUM_EXPERTS,
            hidden_dim=ANSWER_PRETRAIN_HIDDEN_DIM,
        )
        if not os.path.exists(PRETRAIN_CKPT):
            raise FileNotFoundError(f"Missing pretrain checkpoint: {PRETRAIN_CKPT}")
        self.answer_pretrain.load_state_dict(torch.load(PRETRAIN_CKPT, map_location="cpu"))

        # Post trunk
        self.trunk = nn.Sequential(
            nn.Linear(self.Dp, TRUNK_HIDDEN),
            nn.ReLU(),
            nn.Dropout(0.3),
        )

        # Dimension-specific fusion and heads
        dim2idx = {"IE": 0, "SN": 1, "TF": 2, "PJ": 3}
        self.fusions = nn.ModuleDict()
        self.heads = nn.ModuleDict()

        for dim in dims:
            k = len(self.idxs_by_dim[dim])
            fusion = GatedFusion(TRUNK_HIDDEN, k)
            if dim in ("IE", "PJ"):
                fusion.gate.bias.data += 1.0
            self.fusions[dim] = fusion

            self.heads[dim] = nn.Sequential(
                nn.Linear(TRUNK_HIDDEN, HEAD_HIDDEN),
                nn.ReLU(),
                nn.Dropout(0.4 if dim in ("IE", "PJ") else 0.2),
                nn.Linear(HEAD_HIDDEN, 1),
            )

    def forward(self, p_emb):
        B = p_emb.size(0)

        # Answer-pretrain predictions for all 60 questions
        p_e = p_emb.unsqueeze(1).expand(-1, 60, -1)  # (B, 60, Dp)
        q_e = self.q_emb.unsqueeze(0).expand(B, -1, -1).to(p_emb.device)  # (B, 60, Dq)
        d_e = self.dims_onehot.unsqueeze(0).expand(B, -1, -1).to(p_emb.device)  # (B, 60, 4)

        x_w = torch.cat([p_e, q_e, d_e], dim=-1).view(-1, self.inp_dim)  # (B*60, inp_dim)
        preds = self.answer_pretrain(x_w).squeeze(-1).view(B, 60)        # (B, 60)

        trunk_out = self.trunk(p_emb)  # (B, H)

        logits = []
        for dim in dims:
            idxs = self.idxs_by_dim[dim]
            k = len(idxs)

            # Question weights: q_imp * (1 - q_unc), normalized per user
            w_imp = self.q_imp[idxs].unsqueeze(0).expand(B, -1)
            w_unc = (1.0 - self.q_unc[idxs]).unsqueeze(0).expand(B, -1)
            w_new = w_imp * w_unc
            w_new = w_new / (w_new.sum(1, keepdim=True) + EPS)  # (B, k)

            # Dimension summary (k-dim), without q_emb
            summary = preds[:, idxs] * w_new  # (B, k)

            # Shape check for debugging
            assert summary.size(1) == self.fusions[dim].f_sub.in_features, (
                f"{dim}: summary dim {summary.size(1)} != f_sub.in_features {self.fusions[dim].f_sub.in_features}"
            )

            fused = self.fusions[dim](trunk_out, summary)           # (B, H)
            logits.append(self.heads[dim](fused).squeeze(-1))       # (B,)

        return torch.stack(logits, dim=1), preds

# ---- Dataset ----
class MBTIDataset(Dataset):
    def __init__(self, uids, df_meta, df_tgt, user_embs):
        self.uids = uids
        self.df_meta = df_meta
        self.df_tgt = df_tgt
        self.user_embs = user_embs

    def __len__(self):
        return len(self.uids)

    def __getitem__(self, idx):
        u = self.uids[idx]
        emb = torch.tensor(self.user_embs[u], dtype=torch.float32)

        mbti = self.df_meta.loc[u, "type"]
        cls = [0 if mbti[i] == d[0] else 1 for i, d in enumerate(dims)]
        reg = self.df_tgt.loc[u].values.astype(np.float32)

        return emb, torch.tensor(cls, dtype=torch.float32), torch.tensor(reg, dtype=torch.float32)

# ---- Evaluation ----
def evaluate(model, loader):
    model.eval()
    all_t, all_p = [], []
    with torch.no_grad():
        for emb, cls_t, _ in loader:
            emb, cls_t = emb.to(DEVICE), cls_t.to(DEVICE)
            logits, _ = model(emb)
            preds_bin = (torch.sigmoid(logits) >= 0.5).cpu().numpy().astype(int)
            all_p.append(preds_bin)
            all_t.append(cls_t.cpu().numpy())

    y_true = np.vstack(all_t)
    y_pred = np.vstack(all_p)
    f1s = [
        f1_score(y_true[:, i], y_pred[:, i]) if len(np.unique(y_true[:, i])) == 2 else 0.0
        for i in range(len(dims))
    ]
    return f1s, float(np.mean(f1s))

def inspect_prediction_distribution(model, test_loader):
    print("\n== Prediction Distribution ==")
    dim_counts = {d: Counter() for d in dims}
    model.eval()
    with torch.no_grad():
        for emb, _, _ in test_loader:
            emb = emb.to(DEVICE)
            logits, _ = model(emb)
            preds = (torch.sigmoid(logits) >= 0.5).cpu().numpy().astype(int)
            for i, dim in enumerate(dims):
                dim_counts[dim].update(preds[:, i].tolist())

    for dim in dims:
        total = sum(dim_counts[dim].values())
        print(f"{dim}: {dict(dim_counts[dim])}  (Total: {total})")

# ---- Main ----
if __name__ == "__main__":
    # Basic file checks
    for p in [RAW_CSV, ANSWERS_CSV, Q_IMP_CSV, Q_UNCERT_CSV, QUEST_EMB, PRETRAIN_CKPT]:
        if not os.path.exists(p):
            raise FileNotFoundError(f"Missing required file: {p}")

    for split, (emb_path, map_path) in POST_EMB_TM.items():
        if not os.path.exists(emb_path):
            raise FileNotFoundError(f"Missing embedding file: {emb_path}")
        if not os.path.exists(map_path):
            raise FileNotFoundError(f"Missing index map file: {map_path}")

    train_uids_path = os.path.join(SPLIT_DIR, "train_uids.txt")
    test_uids_path  = os.path.join(SPLIT_DIR, "test_uids.txt")
    if not os.path.exists(train_uids_path):
        raise FileNotFoundError(f"Missing split file: {train_uids_path}")
    if not os.path.exists(test_uids_path):
        raise FileNotFoundError(f"Missing split file: {test_uids_path}")

    # Load metadata
    df_all = pd.read_csv(RAW_CSV)
    df_all = ensure_uids_index(df_all)

    # Load roleplay answers (targets for regression auxiliary loss)
    df_4o = pd.read_csv(ANSWERS_CSV, low_memory=False)
    if "uids" not in df_4o.columns:
        raise ValueError("Roleplay answers CSV must contain a 'uids' column.")
    for c in QUESTION_COLS:
        if c not in df_4o.columns:
            raise ValueError(f"Roleplay answers CSV missing column: {c}")

    df_4o[QUESTION_COLS] = df_4o[QUESTION_COLS].apply(pd.to_numeric, errors="coerce")
    df_targets = df_4o.set_index("uids")[QUESTION_COLS].groupby("uids").mean()

    # Load priors
    q_imp_arr = np.array(
        pd.read_csv(Q_IMP_CSV).set_index("question").loc[QUESTION_COLS, "q_importance"],
        dtype=np.float32,
    )
    q_unc_arr = np.array(
        pd.read_csv(Q_UNCERT_CSV).set_index("question").loc[QUESTION_COLS, "q_uncertainty"],
        dtype=np.float32,
    )

    # Load split uids and create validation split from train (user-level)
    train_uids_all = load_uids_txt(train_uids_path)
    test_uids      = load_uids_txt(test_uids_path)

    train_uids, val_uids = train_test_split(
        train_uids_all, test_size=0.1, random_state=42, shuffle=True
    )
    train_uids = sorted(train_uids)
    val_uids   = sorted(val_uids)
    test_uids  = sorted(test_uids)

    df_train = df_all.loc[train_uids + val_uids]
    df_test  = df_all.loc[test_uids]

    # Build per-user post embeddings (mean over post embeddings)
    emb_dict = {}
    for split in ["train", "test"]:
        emb_path, map_path = POST_EMB_TM[split]
        arr = np.load(emb_path)
        mp  = np.load(map_path, allow_pickle=True)
        for (u, _), emb in zip(mp, arr):
            emb_dict.setdefault(int(u), []).append(emb)

    user_embs = {u: np.mean(lst, axis=0) for u, lst in emb_dict.items()}
    if len(user_embs) == 0:
        raise ValueError("No user embeddings were built. Check your embeddings and index maps.")

    # Load question embeddings and build dims one-hot
    q_emb = np.load(QUEST_EMB)
    if q_emb.shape[0] != 60:
        raise ValueError(f"Expected questions embeddings shape (60, Dq), got {q_emb.shape}.")

    q2dim   = get_question2dim()
    dim2idx = {"IE": 0, "SN": 1, "TF": 2, "PJ": 3}
    dims_onehot = np.stack([np.eye(4)[dim2idx[q2dim[q]]] for q in QUESTION_COLS], axis=0)  # (60, 4)

    idxs_by_dim = {d: [] for d in dims}
    for i, q in enumerate(QUESTION_COLS):
        idxs_by_dim[q2dim[q]].append(i)

    print("Per-dimension item counts:", {d: len(idxs_by_dim[d]) for d in dims})

    # Filter uids to those having both meta and embeddings and targets
    def filter_uids(uids):
        out = []
        for u in uids:
            if u in user_embs and u in df_all.index and u in df_targets.index:
                out.append(u)
        return out

    train_uids_f = filter_uids(train_uids)
    val_uids_f   = filter_uids(val_uids)
    test_uids_f  = filter_uids(test_uids)

    if len(train_uids_f) == 0:
        raise ValueError("No valid train users after filtering. Check uids alignment.")
    if len(val_uids_f) == 0:
        raise ValueError("No valid val users after filtering. Check uids alignment.")
    if len(test_uids_f) == 0:
        raise ValueError("No valid test users after filtering. Check uids alignment.")

    # Build loaders
    train_ds = MBTIDataset(train_uids_f, df_train, df_targets, user_embs)
    val_ds   = MBTIDataset(val_uids_f,   df_train, df_targets, user_embs)
    test_ds  = MBTIDataset(test_uids_f,  df_test,  df_targets, user_embs)

    train_ld = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)
    val_ld   = DataLoader(val_ds,   batch_size=BATCH_SIZE)
    test_ld  = DataLoader(test_ds,  batch_size=BATCH_SIZE)

    # Model
    model = DetectModel(
        q_emb=q_emb,
        dims_onehot=dims_onehot,
        q_imp_arr=q_imp_arr,
        q_unc_arr=q_unc_arr,
        user_embs=user_embs,
        idxs_by_dim=idxs_by_dim,
    ).to(DEVICE)

    opt = torch.optim.Adam(model.parameters(), lr=LR)
    cls_crit = nn.BCEWithLogitsLoss()
    reg_crit = nn.MSELoss()

    # Train
    os.makedirs(DETECT_CKPT_DIR, exist_ok=True)
    best_val_f1 = -1.0

    for ep in range(1, EPOCHS + 1):
        model.train()
        total_loss = 0.0

        for emb, cls_t, reg_t in tqdm(train_ld, desc=f"Epoch {ep}"):
            emb, cls_t, reg_t = emb.to(DEVICE), cls_t.to(DEVICE), reg_t.to(DEVICE)

            logits, preds = model(emb)
            loss = cls_crit(logits, cls_t) + LAMBDA_REG * reg_crit(preds, reg_t)

            opt.zero_grad()
            loss.backward()
            opt.step()

            total_loss += loss.item() * emb.size(0)

        avg_loss = total_loss / max(len(train_ld.dataset), 1)
        f1s_val, avg_val = evaluate(model, val_ld)
        print(f"Epoch {ep:02d} Loss={avg_loss:.4f} Val AvgF1={avg_val:.3f} per-dim={f1s_val}")

        if avg_val > best_val_f1:
            best_val_f1 = avg_val
            torch.save(model.state_dict(), BEST_DETECT_PATH)
            print(f"Saved best detect checkpoint to {BEST_DETECT_PATH} (Val AvgF1={avg_val:.3f})")

    # Test with best checkpoint
    print("\n== Best Detect Model Test Evaluation ==")
    model.load_state_dict(torch.load(BEST_DETECT_PATH, map_location=DEVICE))
    model.eval()

    all_preds, all_trues = [], []
    with torch.no_grad():
        for emb, cls_t, _ in test_ld:
            emb = emb.to(DEVICE)
            logits, _ = model(emb)
            preds = (torch.sigmoid(logits) >= 0.5).cpu().numpy().astype(int)
            true = cls_t.numpy()
            all_preds.append(preds)
            all_trues.append(true)

    all_preds = np.vstack(all_preds)
    all_trues = np.vstack(all_trues)

    for i, dim in enumerate(dims):
        f1 = f1_score(all_trues[:, i], all_preds[:, i])
        print(f"{dim}: Test F1 = {f1:.3f}")

    avg_f1 = float(np.mean([f1_score(all_trues[:, i], all_preds[:, i]) for i in range(4)]))
    print(f"Average F1 = {avg_f1:.3f}")

    # Inspect gating weights
    print("\n== Gating Weights (g) per Dimension ==")
    with torch.no_grad():
        emb_sample = next(iter(test_ld))[0].to(DEVICE)
        trunk_out = model.trunk(emb_sample)
        B = emb_sample.size(0)

        q_e = model.q_emb.unsqueeze(0).expand(B, -1, -1).to(DEVICE)
        d_e = model.dims_onehot.unsqueeze(0).expand(B, -1, -1).to(DEVICE)
        p_e = emb_sample.unsqueeze(1).expand(-1, 60, -1)

        wp_all = model.answer_pretrain(
            torch.cat([p_e, q_e, d_e], dim=2).reshape(B * 60, -1)
        ).squeeze(-1).view(B, 60)

        for dim in dims:
            idxs = idxs_by_dim[dim]
            w_imp = model.q_imp[idxs].unsqueeze(0).expand(B, -1)
            w_unc = (1.0 - model.q_unc[idxs]).unsqueeze(0).expand(B, -1)
            w_new = (w_imp * w_unc)
            w_new = w_new / (w_new.sum(1, keepdim=True) + EPS)

            summary = (wp_all[:, idxs] * w_new)  # (B, k)

            assert summary.size(1) == model.fusions[dim].f_sub.in_features

            g_layer = model.fusions[dim].gate
            g_val = torch.sigmoid(g_layer(torch.cat([trunk_out, summary], dim=1)))
            print(f"{dim}: g mean = {g_val.mean().item():.4f}, std = {g_val.std().item():.4f}")

    inspect_prediction_distribution(model, test_ld)
