import os
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import train_test_split
from model_moe import MoE

# ---- Hyperparameters ----
ANSWER_PRETRAIN_NUM_EXPERTS = 32
ANSWER_PRETRAIN_HIDDEN_DIM  = 1024
EPOCHS             = 120
BATCH_SIZE         = 64
LR                 = 5e-4
DEVICE             = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

# ---- Paths (aligned with the current project layout) ----
DATA_DIR       = "data"
EMB_DIR        = os.path.join(DATA_DIR, "embeddings")
SPLIT_DIR      = os.path.join(DATA_DIR, "splits")

# The 4o-generated question-level soft answers (must contain: uids, Q1..Q60)
OUTPUT4O       = os.path.join(DATA_DIR, "roleplay/answers_60_gpt4o.csv")

# Embeddings generated by export_embeddings.py
QUEST_EMB      = os.path.join(EMB_DIR, "question_embeddings.npy")
POST_EMB_TM    = {
    "train": (
        os.path.join(EMB_DIR, "train_post_embeddings.npy"),
        os.path.join(EMB_DIR, "train_post_index_map.npy"),
    ),
    "test": (
        os.path.join(EMB_DIR, "test_post_embeddings.npy"),
        os.path.join(EMB_DIR, "test_post_index_map.npy"),
    ),
}

# Checkpoint directory
CKPT_DIR       = os.path.join("checkpoints", "answer_pretrain")
BEST_CKPT_PATH = os.path.join(CKPT_DIR, "best_pretrain.pth")

# ---- Question->Dimension mapping & one-hot ----
def get_question2dim():
    # Fill the 60-item mapping exactly as previously defined
    return {
        **{f"Q{i}": d for i, d in zip(range(1, 11),  ["IE", "SN", "TF", "PJ", "TF", "IE", "PJ", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(11, 21), ["IE", "SN", "TF", "PJ", "TF", "IE", "SN", "TF", "SN", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(21, 31), ["IE", "SN", "TF", "PJ", "TF", "IE", "TF", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(31, 41), ["IE", "SN", "TF", "PJ", "PJ", "IE", "SN", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(41, 51), ["IE", "SN", "IE", "PJ", "TF", "SN", "TF", "TF", "PJ", "TF"])},
        **{f"Q{i}": d for i, d in zip(range(51, 61), ["IE", "SN", "IE", "TF", "TF", "PJ", "SN", "TF", "PJ", "TF"])},
    }

dim2idx = {"IE": 0, "SN": 1, "TF": 2, "PJ": 3}

# ---- Dataset ----
class AnswerPretrainDataset(Dataset):
    def __init__(self, X, y):
        self.X = X.astype(np.float32)
        self.y = y.astype(np.float32)

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

# ---- Data preparation ----
def prepare_data():
    # 1) Load answers_60_gpt4o.csv and compute per-user mean as regression targets
    if not os.path.exists(OUTPUT4O):
        raise FileNotFoundError(f"Missing file: {OUTPUT4O}")

    df4o = pd.read_csv(OUTPUT4O, low_memory=False)
    QUESTION_COLS = [f"Q{i}" for i in range(1, 61)]

    if "uids" not in df4o.columns:
        raise ValueError("output4o.csv must contain a 'uids' column.")

    missing_q = [c for c in QUESTION_COLS if c not in df4o.columns]
    if missing_q:
        raise ValueError(f"output4o.csv missing question columns: {missing_q}")

    df4o[QUESTION_COLS] = df4o[QUESTION_COLS].apply(pd.to_numeric, errors="coerce")
    df_targets = df4o.groupby("uids", sort=False)[QUESTION_COLS].mean().reset_index()

    # 2) Load post embeddings and aggregate into per-user post embeddings
    emb_dict = {}
    for split, (emb_path, map_path) in POST_EMB_TM.items():
        if not os.path.exists(emb_path):
            raise FileNotFoundError(f"Missing embedding file: {emb_path}")
        if not os.path.exists(map_path):
            raise FileNotFoundError(f"Missing index map file: {map_path}")

        arr = np.load(emb_path)
        mp = np.load(map_path, allow_pickle=True)

        # mp is expected to be a list/array of tuples: (uid, post_idx)
        for (u, _), emb in zip(mp, arr):
            emb_dict.setdefault(int(u), []).append(emb)

    user_embs = {u: np.mean(lst, axis=0) for u, lst in emb_dict.items()}
    if len(user_embs) == 0:
        raise ValueError("No user embeddings were built. Check your embeddings and index maps.")

    # 3) Load question embeddings and build dimension one-hot vectors
    if not os.path.exists(QUEST_EMB):
        raise FileNotFoundError(f"Missing question embeddings: {QUEST_EMB}")

    q_emb = np.load(QUEST_EMB)  # (60, E)
    if q_emb.shape[0] != 60:
        raise ValueError(f"Expected question embeddings shape (60, E), got {q_emb.shape}.")

    q2dim = get_question2dim()
    dims_onehot = np.stack(
        [np.eye(4)[dim2idx[q2dim[f"Q{i}"]]] for i in range(1, 61)],
        axis=0
    )  # (60, 4)

    # 4) Build samples: (user, question) -> concat([p_emb, q_emb[i], dims_onehot[i]]) -> target y
    X_list, y_list = [], []
    for _, row in df_targets.iterrows():
        u = int(row["uids"])
        if u not in user_embs:
            continue

        p = user_embs[u]  # (D_p,)
        for i, q in enumerate(QUESTION_COLS):
            X_list.append(np.concatenate([p, q_emb[i], dims_onehot[i]]))
            y_list.append(row[q])

    if len(X_list) == 0:
        raise ValueError("No training samples were built. Check uids alignment between output4o and embeddings.")

    X = np.stack(X_list)
    y = np.array(y_list, dtype=np.float32)
    X_tr, X_tmp, y_tr, y_tmp = train_test_split(X, y, test_size=0.2, random_state=42)
    X_val, X_te, y_val, y_te = train_test_split(X_tmp, y_tmp, test_size=0.5, random_state=42)

    # 5) Return DataLoaders and input_dim
    train_ds = AnswerPretrainDataset(X_tr, y_tr)
    val_ds   = AnswerPretrainDataset(X_val, y_val)
    test_ds  = AnswerPretrainDataset(X_te, y_te)

    input_dim = q_emb.shape[1] + dims_onehot.shape[1] + len(next(iter(user_embs.values())))

    return (
        DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True),
        DataLoader(val_ds, batch_size=BATCH_SIZE),
        DataLoader(test_ds, batch_size=BATCH_SIZE),
        input_dim,
    )

# ---- Train Pretrain MoE ----
def train_answer_pretrain():
    os.makedirs(CKPT_DIR, exist_ok=True)

    train_ld, val_ld, _, input_dim = prepare_data()
    model = MoE(input_dim, num_experts=ANSWER_PRETRAIN_NUM_EXPERTS, hidden_dim=ANSWER_PRETRAIN_HIDDEN_DIM).to(DEVICE)
    opt   = torch.optim.Adam(model.parameters(), lr=LR)
    crit  = nn.MSELoss()

    best_val = float("inf")
    for ep in range(1, EPOCHS + 1):
        model.train()
        total, cnt = 0.0, 0

        for xb, yb in train_ld:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            pred = model(xb).squeeze(-1)
            loss = crit(pred, yb)

            opt.zero_grad()
            loss.backward()
            opt.step()

            total += loss.item() * xb.size(0)
            cnt += xb.size(0)

        train_loss = total / max(cnt, 1)

        # Validation
        model.eval()
        vtot, vcnt = 0.0, 0
        with torch.no_grad():
            for xb, yb in val_ld:
                xb, yb = xb.to(DEVICE), yb.to(DEVICE)
                vtot += crit(model(xb).squeeze(-1), yb).item() * xb.size(0)
                vcnt += xb.size(0)

        val_loss = vtot / max(vcnt, 1)

        print(f"Epoch {ep:03d}  Train MSE={train_loss:.4f}  Val MSE={val_loss:.4f}")

        if val_loss < best_val:
            best_val = val_loss
            torch.save(model.state_dict(), BEST_CKPT_PATH)
            print(f"  Saved best answer_pretrain checkpoint to: {BEST_CKPT_PATH}")

if __name__ == "__main__":
    train_answer_pretrain()
